version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 1
- package-ecosystem: go
  directory: "/"
  schedule:
    interval: weekly
    time: "04:10"
  open-pull-requests-limit: 1
