version: '3'

includes:
  git: TaskfileGit.yaml
  zsh: TaskfileZsh.yaml
  pyenv: TaskfilePyenv.yaml

tasks:
  install:
    cmds:
      - task: git:install
      - task: zsh:install
      - task: pyenv:install
  config:
    cmds:
      - task: git:config
      - task: zsh:config
      - task: pyenv:config
  default:
    deps:
      [install]