version: '3'

includes:
  deps: TaskfileDeps.yaml
  git: TaskfileGit.yaml
  zsh: TaskfileZsh.yaml

tasks:
  install:
    deps:
      - deps:install
    cmds:
      - task: git:install
      - task: zsh:install
  config:
    deps:
      - git:config
      - zsh:config
  default:
    deps:
      [git:install]