version: '3'

includes:
  git: TaskfileGit.yaml
  zsh: TaskfileZsh.yaml
  docker: TaskfileDocker.yaml
  asdf: TaskfileAsdf.yaml
  atuin: TaskfileAtuin.yaml

tasks:
  install:
    desc: "Installs all"
    cmds:
      - task: git:install
      - task: zsh:install
      - task: docker:install
      - task: asdf:install
      - task: atuin:install
  config:
    desc: "Configures all"
    cmds:
      - task: git:config
      - task: zsh:config
      - task: docker:config
      - task: asdf:config
  default:
    deps:
      [install]