name: Build dotfiles magefile executable

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Test build binary"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Install magefile
        run: go run main.go mage:install

      - name: Build dotfile's executable
        run: mage --compile dotfiles.run
