name: Build dotfiles magefile executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build dotfile's executable
        run: mage --compile dotfiles.run
