name: Go lint and format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run with Mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: go:check:format
