---
name: "pre-release"

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install magefile
        run: go run main.go mage:install

      - name: Build dotfile's executable
        run: mage --compile dotfiles.run

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dotfiles.run